### ISSUE TITLE
Fetch for List of service instances fails

### ISSUE THREAD

**Issue by vinaybheri** [cloudfoundry-community/go-cfclient#244]
I am getting below error while fetching list of service instances.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x679650]

goroutine 1 [running]:
github.com/cloudfoundry-community/go-cfclient.(*Client).NewRequest(...)
        /<$GOPATH>/src/github.com/cloudfoundry-community/go-cfclient/client.go:236
github.com/cloudfoundry-community/go-cfclient.(*Client).ListServiceInstancesByQuery(0x0, 0x0, 0x7782c0, 0xc000298220, 0xc000080de0, 0xc000080e70, 0x2)
        /<$GOPATH>/src/github.com/cloudfoundry-community/go-cfclient/service_instances.go:71 +0x2f0
main.main()
```

I am using code

```
package main

import (
        "github.com/cloudfoundry-community/go-cfclient"
        "fmt"
)

func main() {
        c := &cfclient.Config{
                ApiAddress:   "https://api.<redacted>",
                Username:     "<redacted>",
                Password:     "<redacted>",
                SkipSslValidation: true,
        }

        client, _ := cfclient.NewClient(c)
        instances, err := client.ListServiceInstanes(nil)
        if err != nil {
                fmt.Println(err)
        }
        fmt.Println(instances)

}
```

We have around 75k instances in total.

**Comment by sneal** [comment]
I can't reproduce this. It looks like `cfclient.NewClient(c)` might be returning an unchecked error.
